name: Motorhome
favicon: null
layout_spectrum: 0.7238514244090766
typography_spectrum: 0.09204723569564521
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6986568295396864
  lightness: 0.7600879352539778
  saturation: 0.5438614692538977
  rhythmicContrast: 0.8924044873565435
purpose: []
